# Premium-minds - flowable-keycloak .travis.yml

language: java

# Avoid default OracleJDK7. Complies with Eclipse environment used
jdk:
  - openjdk8

after_success:
  - "./share/deploy/deploy-snapshot.sh"

notifications:
  email:
    recipients:
      - andre.camilo@premium-minds.com
    on_failure: always